#+title: SIGARCH @ UIUC
#+include: header.org
#+ATTR_HTML: :width 300px
[[./resources/sigarch.svg]]

We are the University of Illinois Urbana-Champaign's student-run
computer architecture interest group.

* Meetings
We host weekly meetings *Thursdays* from *5:00-6:00pm* in *ECEB 3013*.
These meetings use a split format, with the first half devoted to the
high level summary of a relevant topic, and the second half devoted to
the discussion of a paper. We're always looking for people interested
in running meetings, so if you have an idea, reach out!
For an archive of past meetings, see [[./meetings.org][here]].

* Workshops
Since *Fall 2023*, we have been hosting semi-regular weekend workshops
directed at giving members hands on exposure to projects in computer
architecture and chip design.
For an archive of past workshops, see [[./workshops.org][here]].

* Join Us
If you're interested in being a part of SIGARCH, join our [[https://discord.gg/DsfB26KjsP][Discord]] to
stay in the loop.

* Frequently Asked Questions
FAQs about computer architecture, SIGARCH, and UIUC
classes are [[./faq.org][here]].

* Sponsors
SIGARCH is looking for sponsorship! If you're interested in sponsoring
us, please email one of ={pradyun2, maiorov2}@illinois.edu=.

* Contact
To get in touch, either message =pradyun= or =mangrovetree0= on Discord, or email one of  ={pradyun2, maiorov2}@illinois.edu=.
